- name: Variables from files
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: Please enter your uername
    private: false
  - name: PASSWORD
    prompt: Please enter your password
    private: true  
  tasks:
  - name: print override information
    ansible.builtin.debug:
     msg: "Hi Username: {{USERNAME}}. password is : {{PASSWORD}}"
